verless/verless

- .bandit
> Add .bandit file

- docs/configuration-reference.md
- docs/template-reference.md
- example/verless.yml
This PR adds the pre-build hooks introduced with #158 to the verless references.
> Add pre-build hooks to references

- core/create.go
> fix: create project inside current directory

- core/create.go
- core/defaults.go
> chore: create default .gitignore file withing new project

- cli/create.go
- core/create.go
Signed-off-by: Samyak Bakliwal <w3bcode@gmail.com>
> fix: add --project flag to create theme for consistency

- model/page.go
- plugin/tags/tags.go
Fix for issue #181 
I don't know how to test is this right or not. 
I will update this PR if any changes are needed.
> fix: initalize routes of list pages

- plugin/tags/tags.go
This PR assigns a route to the list page for `/tags`.
> Assign route to ListPage

- docs/command-reference.md
for changes made in PR #182 #187
> Update docs for command-references

- out/style/style.go
Added the following emojis to the list: 
- Fire
- Sparkles
- Exclamation
- Bulb
- X
- HeavyCheckMark
- Warning
Performed `go fmt` before the commit based on contribution.md instructions.
This fixes #196 
Let me know if you have any issues so I can fix it!
> Add Emojis to out/style/style.go

- fs/fs.go
Replace use of ioutil with io.Copy  
Fixes #200 
I've followed the steps in the contribution guidelines and tried to keep the code-style as similar to the original as possible, please do let me know if I need to make any changes.
> Improve fs.CopyFromOs function

- core/build.go
- core/build_test.go
- model/site.go
- out/style/style.go
- plugin/plugin.go
- theme/theme.go
This PR:
- moves loadPlugins function to its own package(Fixed https://github.com/verless/verless/issues/210)
- fix linters' errors
> Move load plugins

- docs/theme-reference.md
> Add pre-build hooks

- cmd/verless/main.go
- core/serve.go
- core/watch.go
This PR introduces log messages using the new `out` package.
> Improve log messages

- CONTRIBUTING.md
This PR makes the rather firm contribution guidelines a bit more loose, liberated and hopefully more inviting.
> Loosen contribution guidelines

- core/build.go
- example/content/blog/making-barista-quality-espresso.md
- example/themes/default/templates/page.html
- example/verless.yml
- plugin/plugin.go
- plugin/related/related.go
> Implemented related plugin

- core/build.go
- docs/configuration-reference.md
- docs/theme-reference.md
- example/themes/default/theme.yml
- example/verless.yml
- theme/theme.go
> Move page type declarations into theme.yml

- writer/writer.go
> Preserve assets directory structure.

- core/serve.go
- go.mod
- go.sum
> Simplify serve logic and fix deadlock

- core/watch.go
> Add more file events to the watcher

- plugin/atom/atom.go
- plugin/atom/atom_test.go
> Remove too many slashes in atom.xml for Link and ID fixes #248

- core/create.go
> Don't remove .git directory on verless create project

- core/serve.go
> Listen to OS interrupt signal
